const perform = (z, bundle) => {
  const options = {
    url: 'https://app.detrack.com/api/v2/jobs',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'X-API-KEY': bundle.authData.api_key,
    },
    body: {
      data: {
        do_number: bundle.inputData.do_number,
        type: bundle.inputData.type,
        assign_to: bundle.inputData.assign_to,
        open_to_marketplace: bundle.inputData.open_to_marketplace,
        address: bundle.inputData.address,
        date: bundle.inputData.date,
        items: bundle.inputData.items,
      },
    },
  };

  return z.request(options).then((response) => {
    // response.throwForStatus();
    const results = z.JSON.parse(response.content);

    // You can do any parsing you need for results here before returning them

    return results;
  });
};

module.exports = {
  operation: {
    perform: perform,
    inputFields: [
      {
        key: 'do_number',
        label: 'DO Number',
        type: 'string',
        helpText:
          'DO Number of the Job. Must be unique among all jobs in the same day.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'type',
        label: 'Job Type',
        type: 'string',
        default: 'delivery',
        helpText: 'Job Type, either Delivery or Collection',
        choices: ['delivery', 'collection'],
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'address',
        label: 'Address',
        type: 'string',
        helpText: '*Full address* of the job destination.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'date',
        label: 'Date',
        type: 'datetime',
        helpText:
          'Date to save this job to in the Detrack Dashboard. **Must be in format** `YYYY-MM-DD`',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'assign_to',
        label: 'Assign To Driver',
        type: 'string',
        helpText:
          'Enter the name of a vehicle to automatically assign this job to that vehicle.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'items',
        children: [
          {
            key: 'sku',
            label: 'SKU',
            type: 'string',
            helpText:
              'Stock Keeping Unit to represent the type of item being sent in this Job',
            required: true,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'description',
            label: 'Description',
            type: 'string',
            helpText:
              '**Required if SKU is blank**. A human readable description of what this item contains. E.g. ice cream.',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'qty',
            label: 'Quantity',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'comments',
            label: 'Comments',
            type: 'string',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
          {
            key: 'weight',
            label: 'Weight',
            type: 'number',
            required: false,
            list: false,
            altersDynamicFields: false,
          },
        ],
        label: 'Create Job Items',
        required: false,
        altersDynamicFields: false,
      },
      {
        key: 'open_to_marketplace',
        label: 'Open To Marketplace?',
        type: 'boolean',
        helpText:
          'For marketplace mode, whether this job will be opened to the marketplace for drivers to bid',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'meta',
        label: 'meta',
        dict: true,
        required: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      data: {
        id: '5b22055510c92b1a046ece04',
        type: 'Delivery',
        primary_job_status: 'dispatched',
        open_to_marketplace: false,
        marketplace_offer: null,
        do_number: 'DO 0',
        attempt: 1,
        date: '2018-06-14',
        start_date: '2018-06-14',
        job_age: 1,
        job_release_time: null,
        job_time: null,
        time_window: null,
        job_received_date: null,
        tracking_number: 'T0',
        order_number: 'ORN12345678',
        job_type: null,
        job_sequence: null,
        job_fee: null,
        address_lat: null,
        address_lng: null,
        address: 'Singapore 470140',
        company_name: null,
        address_1: null,
        address_2: null,
        address_3: null,
        postal_code: '470140',
        city: null,
        state: null,
        country: null,
        geocoded_lat: 1.33668219002454,
        geocoded_lng: 103.910711702473,
        billing_address: null,
        deliver_to_collect_from: 'James Li',
        last_name: null,
        phone_number: '65432178',
        sender_phone_number: null,
        fax_number: '65432179',
        instructions: null,
        assign_to: null,
        notify_email: 'daniel@detrack.com',
        webhook_url: null,
        zone: null,
        customer: null,
        account_no: null,
        job_owner: null,
        invoice_number: null,
        invoice_amount: null,
        payment_mode: null,
        payment_amount: null,
        group_name: null,
        vendor_name: null,
        shipper_name: null,
        source: null,
        weight: null,
        parcel_width: null,
        parcel_length: null,
        parcel_height: null,
        cubic_meter: null,
        boxes: null,
        cartons: null,
        pieces: null,
        envelopes: null,
        pallets: null,
        bins: null,
        trays: null,
        bundles: null,
        rolls: null,
        number_of_shipping_labels: null,
        attachment_url: null,
        detrack_number: 'DET2000001',
        status: 'dispatched',
        tracking_status: 'Info received',
        reason: null,
        last_reason: null,
        received_by_sent_by: null,
        note: null,
        carrier: null,
        pod_lat: '',
        pod_lng: '',
        pod_address: '',
        address_tracked_at: null,
        arrived_lat: null,
        arrived_lng: null,
        arrived_address: null,
        arrived_at: null,
        texted_at: null,
        called_at: null,
        serial_number: null,
        signed_at: null,
        photo_1_at: null,
        photo_2_at: null,
        photo_3_at: null,
        photo_4_at: null,
        photo_5_at: null,
        signature_file_url: null,
        photo_1_file_url: null,
        photo_2_file_url: null,
        photo_3_file_url: null,
        photo_4_file_url: null,
        photo_5_file_url: null,
        actual_weight: null,
        temperature: null,
        hold_time: null,
        payment_collected: null,
        auto_reschedule: null,
        actual_crates: null,
        actual_pallets: null,
        actual_utilization: null,
        goods_service_rating: null,
        driver_rating: null,
        customer_feedback: null,
        eta_time: null,
        live_eta: null,
        depot: null,
        depot_contact: null,
        department: null,
        sales_person: null,
        identification_number: null,
        bank_prefix: null,
        run_number: null,
        pick_up_from: null,
        pick_up_time: null,
        pick_up_lat: null,
        pick_up_lng: null,
        pick_up_address: null,
        pick_up_address_1: null,
        pick_up_address_2: null,
        pick_up_address_3: null,
        pick_up_city: null,
        pick_up_state: null,
        pick_up_country: null,
        pick_up_postal_code: null,
        pick_up_zone: null,
        pick_up_assign_to: null,
        pick_up_reason: null,
        info_received_at: '2018-06-14T06:04:06.017Z',
        pick_up_at: null,
        scheduled_at: null,
        at_warehouse_at: null,
        out_for_delivery_at: null,
        head_to_pick_up_at: null,
        head_to_delivery_at: null,
        cancelled_at: null,
        pod_at: null,
        pick_up_failed_count: null,
        deliver_failed_count: null,
        job_price: null,
        insurance_price: null,
        insurance_coverage: false,
        total_price: null,
        payer_type: null,
        remarks: null,
        items_count: 2,
        service_type: null,
        warehouse_address: null,
        destination_time_window: null,
        door: null,
        time_zone: null,
        created_at: '2018-06-14T06:04:06.017Z',
        items: [
          {
            id: '5b22055510c92b1a046ece05',
            sku: '12345678',
            purchase_order_number: null,
            batch_number: null,
            expiry_date: null,
            description: null,
            comments: null,
            quantity: 10,
            unit_of_measure: null,
            checked: false,
            actual_quantity: null,
            inbound_quantity: null,
            unload_time_estimate: null,
            unload_time_actual: null,
            follow_up_quantity: null,
            follow_up_reason: null,
            rework_quantity: null,
            rework_reason: null,
            reject_quantity: 0,
            reject_reason: null,
            weight: null,
            serial_numbers: [],
            photo_url: null,
          },
          {
            id: '5b22055510c92b1a046ece06',
            sku: '12387654',
            purchase_order_number: null,
            batch_number: null,
            expiry_date: null,
            description: null,
            comments: null,
            quantity: 5,
            unit_of_measure: null,
            checked: false,
            actual_quantity: null,
            inbound_quantity: null,
            unload_time_estimate: null,
            unload_time_actual: null,
            follow_up_quantity: null,
            follow_up_reason: null,
            rework_quantity: null,
            rework_reason: null,
            reject_quantity: 0,
            reject_reason: null,
            weight: null,
            serial_numbers: [],
            photo_url: null,
          },
        ],
      },
    },
    outputFields: [
      {key: 'data__id', label: 'Job Id'},
      {key: 'data__type', label: 'Type', type: 'string'},
      {key: 'data__primary_job_status', label: 'Primary Job Status'},
      {
        key: 'data__open_to_marketplace',
        label: 'Open To MarketPlace',
        type: 'boolean',
      },
      {key: 'data__marketplace_offer', label: 'Marketplace Offer'},
      {key: 'data__do_number', label: 'DO Number'},
      {key: 'data__attempt', label: 'Attempt No.', type: 'integer'},
      {key: 'data__date', type: 'datetime', label: 'Date'},
      {key: 'data__start_date', label: '(Custom field) Start Date'},
      {key: 'data__job_age', label: 'Job Age'},
      {
        key: 'data__job_release_time',
        label: '(Custom field) Job Release Time',
      },
      {key: 'data__job_time', label: '(Custom field) Job Time'},
      {key: 'data__time_window', label: 'Time Window'},
      {
        key: 'data__job_received_date',
        label: '(Custom field) Job Received Date',
      },
      {key: 'data__tracking_number', label: '(Custom field) Tracking number'},
      {key: 'data__order_number', label: '(Custom field) Order number'},
      {key: 'data__job_type', label: '(Custom field) Job Type'},
      {key: 'data__job_sequence', label: 'Job Sequence', type: 'number'},
      {key: 'data__job_fee', label: '(Custom field) Job fee'},
      {key: 'data__address_lat', type: 'number', label: 'Address Latitude'},
      {key: 'data__address_lng', label: 'Address Longitude'},
      {key: 'data__address', label: 'Address (full)'},
      {key: 'data__company_name', label: '(Custom field) Company name'},
      {key: 'data__address_1', label: 'Address Line 1 (Partial Addresses)'},
      {key: 'data__address_2', label: 'Address Line 2 (Partial Addresses)'},
      {key: 'data__address_3', label: 'Address Line 3 (Partial Addresses)'},
      {
        key: 'data__postal_code',
        label: 'Address Postal Code (Partial Addresses)',
      },
      {key: 'data__city', label: 'Address City (Partial Addresses)'},
      {key: 'data__state', label: 'Address State (Partial Addresses)'},
      {key: 'data__country', label: 'Address Country (Partial Addresses)'},
      {key: 'data__geocoded_lat', label: 'Geocoded Latitude'},
      {key: 'data__geocoded_lng', label: 'Geocoded Longitude'},
      {key: 'data__billing_address', label: 'Billing Address'},
      {
        key: 'data__deliver_to_collect_from',
        label: '(Custom Field) Name of the Recipient or Sender',
      },
      {
        key: 'data__last_name',
        label: '(Custom Field) Last name of the Recipient or Sender',
      },
      {key: 'data__phone_number', label: 'Phone Number'},
      {key: 'data__sender_phone_number', label: 'Sender Phone Number'},
      {key: 'data__fax_number', label: '(Custom Field) Fax Number'},
      {
        key: 'data__instructions',
        label: 'Text for your driver in the Driver App',
      },
      {
        key: 'data__assign_to',
        label: 'The vehicle/driver assigned to the job',
      },
      {
        key: 'data__notify_email',
        label: 'Email Addresses to send notifications to, separated with ";"',
      },
      {key: 'data__webhook_url', label: 'Webhook URL'},
      {key: 'data__zone', label: 'Zone'},
      {key: 'data__customer', label: '(Custom Field) Customer Name'},
      {key: 'data__account_no', label: '(Custom Field) Account Number'},
      {key: 'data__job_owner', label: '(Custom Field) Job Owner'},
      {key: 'data__invoice_number', label: '(Custom Field) Invoice Number'},
      {
        key: 'data__invoice_amount',
        label: '(Custom Field) Invoice Amount',
        type: 'number',
      },
      {key: 'data__payment_mode', label: 'Payment Mode'},
      {key: 'data__payment_amount', label: 'Payment Amount', type: 'number'},
      {key: 'data__group_name', label: 'Group Name'},
      {key: 'data__vendor_name', label: '(Custom Field) Vendor Name'},
      {key: 'data__shipper_name', label: '(Custom Field) Shipper Name'},
      {key: 'data__source', label: '(Custom Field) Source'},
      {key: 'data__weight', label: 'Weight', type: 'number'},
      {key: 'data__parcel_width', label: 'Parcel Width', type: 'integer'},
      {key: 'data__parcel_length', label: 'Parcel Length', type: 'integer'},
      {key: 'data__parcel_height', label: 'Parcel Height', type: 'integer'},
      {
        key: 'data__cubic_meter',
        label: 'Volume in Cubic Meters',
        type: 'number',
      },
      {key: 'data__boxes', label: 'Boxes', type: 'integer'},
      {key: 'data__cartons', label: 'Cartons', type: 'integer'},
      {key: 'data__pieces', label: 'Pieces', type: 'integer'},
      {key: 'data__envelopes', label: 'Envelopes', type: 'integer'},
      {key: 'data__pallets', label: 'Pallets', type: 'integer'},
      {key: 'data__bins', label: 'Bins', type: 'integer'},
      {key: 'data__trays', label: 'Trays', type: 'integer'},
      {key: 'data__bundles', label: 'Bundles', type: 'integer'},
      {key: 'data__rolls', label: 'Rolls', type: 'integer'},
      {
        key: 'data__number_of_shipping_labels',
        label: 'Number of Shipping Labels To Be Generated',
        type: 'integer',
      },
      {key: 'data__attachment_url', label: 'Attachment URL'},
      {key: 'data__detrack_number', label: 'Detrack Number'},
      {key: 'data__status', label: 'Status'},
      {key: 'data__tracking_status', label: 'Tracking Status'},
      {key: 'data__reason', label: 'Reason'},
      {key: 'data__last_reason', label: 'Last Reason'},
      {key: 'data__received_by_sent_by', label: 'Received By Sent By Name'},
      {key: 'data__note', label: 'Note'},
      {key: 'data__carrier', label: 'Carrier'},
      {key: 'data__pod_lat', label: 'POD Latitude', type: 'number'},
      {key: 'data__pod_lng', label: 'POD Longitude', type: 'number'},
      {key: 'data__pod_address', label: 'POD Address'},
      {
        key: 'data__address_tracked_at',
        label: 'Address Tracket At',
        type: 'datetime',
      },
      {key: 'data__arrived_lat', label: 'Arrived Latitude', type: 'number'},
      {key: 'data__arrived_lng', label: 'Arrived Longitude', type: 'number'},
      {key: 'data__arrived_address', label: 'Arrived Address'},
      {key: 'data__arrived_at', label: 'Arrived At', type: 'datetime'},
      {key: 'data__texted_at', label: 'Texted At', type: 'datetime'},
      {key: 'data__called_at', label: 'Called At', type: 'datetime'},
      {key: 'data__serial_number', label: 'Serial Number'},
      {key: 'data__signed_at', label: 'Signed At', type: 'datetime'},
      {key: 'data__photo_1_at', label: 'Photo 1 Taken At', type: 'datetime'},
      {key: 'data__photo_2_at', label: 'Photo 2 Taken At', type: 'datetime'},
      {key: 'data__photo_3_at', label: 'Photo 3 Taken At', type: 'datetime'},
      {key: 'data__photo_4_at', label: 'Photo 4 Taken At', type: 'datetime'},
      {key: 'data__photo_5_at', label: 'Photo 5 Taken At', type: 'datetime'},
      {key: 'data__signature_file_url', label: 'Signature File URL'},
      {key: 'data__photo_1_file_url', label: 'Photo 1 File URL'},
      {key: 'data__photo_2_file_url', label: 'Photo 2 File URL'},
      {key: 'data__photo_3_file_url', label: 'Photo 3 File URL'},
      {key: 'data__photo_4_file_url', label: 'Photo 4 File URL'},
      {key: 'data__photo_5_file_url', label: 'Photo 5 File URL'},
      {
        key: 'data__actual_weight',
        label: '(Custom Field) Actual Weight',
        type: 'number',
      },
      {
        key: 'data__temperature',
        label: '(Custom Field) Temperature',
        type: 'number',
      },
      {key: 'data__hold_time', label: 'Hold Time', type: 'number'},
      {
        key: 'data__payment_collected',
        label: 'Payment Collected',
        type: 'number',
      },
      {
        key: 'data__auto_reschedule',
        label: 'Auto Reschedule?',
        type: 'boolean',
      },
      {key: 'data__actual_crates', label: 'Actual Crates', type: 'integer'},
      {key: 'data__actual_pallets', type: 'integer', label: 'Actual Pallets'},
      {
        key: 'data__actual_utilization',
        label: 'Actual Utilization',
        type: 'number',
      },
      {
        key: 'data__goods_service_rating',
        type: 'integer',
        label: 'Goods Service Rating',
      },
      {key: 'data__driver_rating', type: 'integer', label: 'Driver Rating'},
      {
        key: 'data__customer_feedback',
        type: 'string',
        label: 'Customer Feedback',
      },
      {key: 'data__eta_time', label: 'Estimated Time of Arrival'},
      {key: 'data__live_eta', label: 'Live Estimated Time of Arrival'},
      {key: 'data__depot', label: 'Depot'},
      {key: 'data__depot_contact', label: '(Custom Field) Depot Contact'},
      {key: 'data__department', label: '(Custom Field) Department'},
      {key: 'data__sales_person', label: '(Custom Field) Sales Person'},
      {
        key: 'data__identification_number',
        label: '(Custom Field) Identification Number',
      },
      {key: 'data__bank_prefix', label: '(Custom Field) Bank Prefix'},
      {key: 'data__run_number', label: 'Run Number', type: 'number'},
      {key: 'data__pick_up_from', label: 'Pick Up From'},
      {key: 'data__pick_up_time', label: 'Pick Up Time', type: 'datetime'},
      {key: 'data__pick_up_lat', label: 'Pick Up Latitude', type: 'datetime'},
      {
        key: 'data__pick_up_lng',
        label: 'Pick Up Longitude',
        type: 'datetime',
      },
      {key: 'data__pick_up_address', label: 'Pick Up Address'},
      {key: 'data__pick_up_address_1', label: 'Pick Up Address Line 1'},
      {key: 'data__pick_up_address_2', label: 'Pick Up Address Line 2'},
      {key: 'data__pick_up_address_3', label: 'Pick Up Address Line 3'},
      {key: 'data__pick_up_city', label: 'Pick Up Address City'},
      {key: 'data__pick_up_state', label: 'Pick Up Address State'},
      {key: 'data__pick_up_country', label: 'Pick Up Address Country'},
      {key: 'data__pick_up_postal_code', label: 'Pick Up Postal Code'},
      {key: 'data__pick_up_zone', label: 'Pick Up Zone'},
      {key: 'data__pick_up_assign_to', label: 'Pick Up Assign To'},
      {key: 'data__pick_up_reason', label: 'Pick Up Reason'},
      {
        key: 'data__info_received_at',
        label: 'Info Received At',
        type: 'datetime',
      },
      {key: 'data__pick_up_at', label: 'Pick Up At', type: 'datetime'},
      {key: 'data__scheduled_at', label: 'Scheduled At', type: 'datetime'},
      {
        key: 'data__at_warehouse_at',
        label: 'At Warehouse At',
        type: 'datetime',
      },
      {
        key: 'data__out_for_delivery_at',
        label: 'Out For Delivery At',
        type: 'datetime',
      },
      {
        key: 'data__head_to_pick_up_at',
        label: 'Head To Pick Up At',
        type: 'datetime',
      },
      {
        key: 'data__head_to_delivery_at',
        label: 'Head To Delivery At',
        type: 'datetime',
      },
      {key: 'data__cancelled_at', label: 'Cancelled At', type: 'datetime'},
      {key: 'data__pod_at', label: 'POD At', type: 'datetime'},
      {
        key: 'data__pick_up_failed_count',
        label: 'Pick Up Failed Count',
        type: 'integer',
      },
      {
        key: 'data__deliver_failed_count',
        label: 'Deliver Failed Count',
        type: 'integer',
      },
      {key: 'data__job_price', label: 'Job Price', type: 'number'},
      {
        key: 'data__insurance_price',
        label: 'Insurance Price',
        type: 'number',
      },
      {
        key: 'data__insurance_coverage',
        label: 'Insurance Coverage',
        type: 'boolean',
      },
      {key: 'data__total_price', label: 'Total Price', type: 'number'},
      {key: 'data__payer_type', label: 'Payer Type'},
      {key: 'data__remarks', label: 'Remarks'},
      {key: 'data__items_count', label: 'Items Count'},
      {key: 'data__service_type', label: 'Service Type'},
      {key: 'data__warehouse_address', label: 'Warehouse Address'},
      {
        key: 'data__destination_time_window',
        label: 'Destination Time Window',
      },
      {key: 'data__door', label: 'Door'},
      {key: 'data__time_zone', label: 'Time Zone'},
      {key: 'data__created_at', label: 'Created At', type: 'datetime'},
      {key: 'data__items[]id', label: 'Id'},
      {key: 'data__items[]sku', label: 'SKU'},
      {
        key: 'data__items[]purchase_order_number',
        label: 'Purchase Order Number',
      },
      {key: 'data__items[]batch_number', label: 'Batch Number'},
      {key: 'data__items[]expiry_date', label: 'Expiry Date'},
      {key: 'data__items[]description', label: 'Description'},
      {key: 'data__items[]comments', label: 'Comments'},
      {key: 'data__items[]quantity', label: 'Quantity'},
      {key: 'data__items[]unit_of_measure', label: 'Unit of Measure'},
      {key: 'data__items[]checked', label: 'Checked'},
      {
        key: 'data__items[]actual_quantity',
        label: 'Actual Quantity',
        type: 'integer',
      },
      {
        key: 'data__items[]inbound_quantity',
        label: 'Inbound Quantity',
        type: 'integer',
      },
      {
        key: 'data__items[]unload_time_estimate',
        label: 'Unload Time Estimate',
        type: 'integer',
      },
      {
        key: 'data__items[]unload_time_actual',
        label: 'Unload Time Actual',
        type: 'integer',
      },
      {
        key: 'data__items[]follow_up_quantity',
        label: 'Follow Up Quantity',
        type: 'integer',
      },
      {key: 'data__items[]follow_up_reason', label: 'Follow Up Reason'},
      {
        key: 'data__items[]rework_quantity',
        label: 'Rework Quantity',
        type: 'integer',
      },
      {key: 'data__items[]rework_reason', label: 'Rework Reason'},
      {
        key: 'data__items[]reject_quantity',
        label: 'Reject Quantity',
        type: 'integer',
      },
      {key: 'data__items[]reject_reason', label: 'Reject Reason'},
      {key: 'data__items[]weight', label: 'Weight', type: 'number'},
      {key: 'data__items[]photo_url', label: 'Photo URL'},
    ],
  },
  key: 'create_job',
  noun: 'Job',
  display: {
    label: 'Create Job',
    description: 'Creates a job in the Detrack Dashboard',
    hidden: false,
    important: true,
  },
};
